### PR TITLE
changing host and port on dsn string

### PR DESCRIPTION
**Pull request by meilhamfadil**
I cannot connect to my databse, when using another port for postgre, 
the dsn host cannot contian port, so i try to replace the dsn host
thanks

### CODE REVIEW

**Comment by izniburak** [comment]
What's the dns that you tried to use? 
You can already separate host and port and use them via 'host' and 'port' config variables.

**Comment by meilhamfadil** [comment]
the dns result is = postgre:host=127.0.0.1:1000;port:1000
what i need is = postgre:host=127.0.0.1;port:1000

i can't pass port config from constructor, because the port config variable is from config host string
line 93 : $config['port'] = (strstr($config['host'], ':') ? explode(':', $config['host'])[1] : '');

**Comment by izniburak** [comment]
I couldn't understand why you can pass ip:port to `host` in config variable? It must be like that:
```php
$config = [
  'host' => '127.0.0.1',
  'port' => 1000,
  // other values...
];
```
I think value of your `$config['host']` is `127.0.0.1:1000`. Right?

**Comment by meilhamfadil** [comment]
yes, the $config['host'] value is 127.0.0.1:1000
but when i use 
$config = [
  'host' => '127.0.0.1',
  'port' => 1000,
  // other values...
];

it doesn't work

**Comment by izniburak** [comment]
Hi, 
Okay, I see. I just checked the problem you mentioned. We can merge this PR. After, I will make some improvements about that problem. 

Thanks.

**Comment by izniburak** [comment]
I just released a new version about this issue. You can update your package via composer or manually.
Thanks.

**Comment by meilhamfadil** [comment]
okay, thanks for your updates
sorry for my late response

**Pull request merged**
