### PR TITLE
Fixing table function parameter handling bugs

### PR DESCRIPTION
**Pull request by imsole**
A problem I encountered when using table functions，

`$db->table('table1, table2');`
Output: `"SELECT * FROM table1, table2" `

The output is like this ： `select from prefix_table1, table2`
But what I expect is the result： `select from prefix_table1, prefix_table2`,

So, I'll fix some of the code.

### CODE REVIEW

**Comment by imsole** [comment]
```
public function join($table, $field1 = null, $op = null, $field2 = null, $type = '')
    {
        $on = $field1;
        $table = $this->prefix . $table;

        if (! is_null($op)) {
            // $this->prefix . $field1， It doesn't seem right here. 
            $on = (! in_array($op, $this->op) ?
                $this->prefix . $field1 . ' = ' . $this->prefix . $op :
                $this->prefix . $field1 . ' ' . $op . ' ' . $this->prefix . $field2);
        }

        if (is_null($this->join)) {
            $this->join = ' ' . $type . 'JOIN' . ' ' . $table . ' ON ' . $on;
        } else {
            $this->join = $this->join . ' ' . $type . 'JOIN' . ' ' . $table . ' ON ' . $on;
        }

        return $this;
    }
```

**Comment by izniburak** [comment]
Hi @imsole ,
Thanks for your contributing. I've reviewed your PR, so you're right. This is a bug and we can fix this. But your PR is contain some Chinese texts. Can you translate these to English from Chinese or create a new PR that just contain the bugfix? If you can't, I can do this.

Thanks.

**Comment by imsole** [comment]
Okay, I've got it.

**Comment by izniburak** [comment]
Hi @imsole , you have changed original documentation file. Could you please remove the commit regarding to this or create a new PR that just contain your changes?

Thanks.

**Comment by imsole** [comment]
Got it done.

**Comment by izniburak** [comment]
Thank you!

**Pull request merged**
